language:
  - node_js

node_js:
  - 6
  - 4

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

branches:
  except:
    # Don't run on tag pushes
    - /^v\d+\.\d+\.\d+$/

install:
  - npm update
  - npm prune

script:
  - npm test

after_success:
  - git config --global user.email "ci@smartcar.com"
  - git config --global user.name "Travis CI User"

  # only run git tag on master branch. which includes PR builds
  - if [ "$(TRAVIS_BRANCH)" = "master" ]; then git tag -a v$(prod_image_tag) -m "Travis Generated Tag"; fi

deploy:
  provider: script
  skip_cleanup: true
  script: git tag origin $(grep \"version\" package.json | sed 's/[", ]//g' | cut -d : -f 2)
  on:
    branch: master
    node: node
