language:
  - node_js

node_js:
  - 6
  - 4


cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

branches:
  except:
    # Don't run on tag pushes
    - /^v\d+\.\d+\.\d+$/

install:
  - git clone git@github.com:smartcar/build.git $HOME/smartcar-build
  - cp $HOME/smartcar-build/resources/Makefile .

  - npm update
  - npm prune

script:
  - npm test

after_success:
  - make create-tag

deploy:
  provider: script
  skip_cleanup: true
  script: make push-tag
  on:
    branch: master
    node: node
